markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'
paginate_path: "/page:num/"


name: 'Adventurous J'
description: "J`s Travel and Tech"

baseurl: /
url: https://adventurousj.github.io
short_url: 'adventurousj.github.io/'
google_analytics: UA-140457165-1
disqus: adventurousj

permalink: /:title

plugins: [jekyll-paginate]


exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
